[bumpver]
current_version = "0.0.1-alpha10"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"build.gradle" = [
    "version = '{version}'"
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
