name: Build 'n Deploy
on: push
jobs:
  build-api:
    name: build, lint, and test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: gradle build
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: build-libs
          path: build/libs/*.jar
